language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew bintrayUpload"
env:
  global:
  - BINTRAY_USER=pwielgolaski
  - secure: aZxaHxAD7p5vwxDJzvy70pvomiZ14qhf51TfUjSW51riGihpBv4yAP0lK0y5Lcx/nphPhZsnSxxTJsmmd2obYL9kkZzlcrqMCt6taTJY/b5vtkcNN8JYmP6/cPQCIJPt9KMrdfpfp0X2lNJdMQvpfFHkP6B8vT+tNpd9ylhCHFai7s6o4t4FaxEtfT2RgxB+6j1fohnY6/BoLHHYcpE0lad5JyirjxhFCXN3eMeP5FHgkJ/7vPcys2Q9XGPI8aQl95kFFPGk0foi7gEfFYK+XLkflU+tFmBLOlKiUJ23xbXnU+38wrVLfibgt6R+W2GNXXJGk0+cw0R6cC/8of5nm9X/28inGx80fcpBS0vyT6lp91b9jslH8B75l79cHg3Hte3+OV61dfrrkYXB5sEyTPuFS+u5sfwnj69vrqHkYby9Hjl0pmBLVgDlOILNL4z9UWCKIw1HY5pgT9X6bV3ege6qqOolm0/DbMyYez/xXN+4nSFrSWilFD0vzriTTOYVxxW+WYouxNKnw7rdZaCU1ExcmbX0UX2uymxCy/gVgJPFzZgm6YC4AylI7zHPUD9Nwta3kBO1B0SRJMYLg/uHDQiKCc0Upezgk5BlbDIzGYiwluonl76PP80QElRWPo0f2ms0AS2fjLLzGAAak6kqkebEC9eCmm94y9tRH+HwvgM=
